<?php return array (
  'title' => '博客',
  'local' => true,
  'name' => 'Blog',
  'thumb' => 'modules/blog/thumb.jpeg',
  'config' => '1',
  'domain' => '1',
  'wx_replies' => '1',
  'wx_cover' => '1',
  'menu_web' => false,
  'menu_mobile' => false,
  'subscribe' => '1',
  'processor' => false,
  'home_pc' => '1',
  'space_pc' => '1',
  'space_mobile' => '1',
  'version' => 1554826124,
);