<?php return array (
  'title' => '文档库',
  'local' => true,
  'name' => 'Document',
  'thumb' => 'modules/document/thumb.jpeg',
  'config' => '1',
  'domain' => '1',
  'wx_replies' => '1',
  'wx_cover' => '1',
  'menu_web' => false,
  'menu_mobile' => false,
  'subscribe' => '1',
  'processor' => false,
  'home_pc' => '1',
  'space_pc' => '1',
  'space_mobile' => '1',
  'version' => 1553261703,
);