<?php return array (
  'title' => '在线教育',
  'local' => true,
  'name' => 'Edu',
  'thumb' => 'modules/edu/thumb.jpeg',
  'config' => '1',
  'domain' => '1',
  'wx_replies' => '1',
  'wx_cover' => '1',
  'menu_web' => false,
  'menu_mobile' => false,
  'subscribe' => '1',
  'processor' => false,
  'home_pc' => '1',
  'space_pc' => '1',
  'space_mobile' => '1',
  'version' => 1551880530,
);